### ISSUE TITLE
Handle spaces in filenames

### ISSUE THREAD

**Issue by acathrow** [anchore/anchore#15]
the filelist analyzer uses awk to extract file names and permissions

  tar tvf $UNPACKDIR/squashed.tar | awk '{print $6, $1}' | sort -k 1 | uniq > $OUTPUTDIR/files.all

In cases where a filename contains spaces then only the first part of the filename, preceding the space, will be retrieved.

**Comment by nurmi** [comment]
anchore 1.0.X queries and output formatting supports spaces in filenames
