### ISSUE TITLE
A CHANGELOG.rst file would be very helpful

### ISSUE THREAD

**Issue by AndyBerman** [anchore/anchore#19]
I'm having a hard time finding out what's changed in version 1.0.2 or 1.0.3

**Comment by acathrow** [comment]
Thanks Andy we'll get that fixed.
Some of the most notable improvements you'll see is support for NPM module and content-search-matches that allow you to search for file contents as well as specific files. 
But we'll make sure we add a changelog.

**Comment by nurmi** [comment]
Thank you Andy - I've just now created a CHANGELOG.md and committed, we will keep this log up-to-date and updated when future releases are tagged!

https://github.com/anchore/anchore/blob/master/CHANGELOG.md
