### ISSUE TITLE
Readme instructions are not working

### ISSUE THREAD

**Issue by Wajihulhassan** [anchore/anchore#23]
I followed all the instructions on README to built anchore. But I am getting error when I run following command:
```
anchore analyze --image nginx:latest --imagetype base
Analyzing image: nginx:latest
5e69fe4b3c31: analyzing ...
ERROR analyzer status: failed
ERROR analyzer exitcode: 1
ERROR analyzer output: Traceback (most recent call last):
  File "/home/wajih/.local/lib/python2.7/site-packages/anchore/anchore_utils.py", line 2076, in get_files_from_path
    os.chroot(inpath)
OSError: [Errno 1] Operation not permitted: '/home/wajih/.anchore/anchoretmp/5451369.anchoretmp/rootfs'
Traceback (most recent call last):
  File "/home/wajih/.local/lib/python2.7/site-packages/anchore/anchore-modules/analyzers/12_gem_package_list.py", line 38, in <module>
    fmap, allfiles = anchore.anchore_utils.get_files_from_path(unpackdir + "/rootfs")
  File "/home/wajih/.local/lib/python2.7/site-packages/anchore/anchore_utils.py", line 2151, in get_files_from_path
    os.chroot('.')
OSError: [Errno 1] Operation not permitted: '.'
[Errno 1] Operation not permitted: '/home/wajih/.anchore/anchoretmp/5451369.anchoretmp/rootfs'
Traceback (most recent call last):
  File "/home/wajih/.local/lib/python2.7/site-packages/anchore/anchore-modules/analyzers/12_gem_package_list.py", line 61, in <module>
    raise err
OSError: [Errno 1] Operation not permitted: '.'

ERROR analyzer failed to run on image 5e69fe4b3c310ea91ead6008e143deca87995d0519f258008cc52e8c0a5366da, skipping the rest
ERROR analyzers failed to run on one or more images.
ERROR analysis failed.
ERROR analysis failed for one or more images.
```
Any help would be appreciated.

Docker version 17.03.0-ce, build 3a232c8
pip 9.0.1 from /usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)

**Comment by acathrow** [comment]
We use chroot during the image extraction to handle links in the image, otherwise the local filesystem could be impacted - so we require root for that. 
We'll get the readme updated to cover that.

**Comment by nurmi** [comment]
Greetings,

Another approach that may work well for you, depending on your environment, might be to work with a container that has anchore installed (or within which you install anchore).  We have some containers hosted on dockerhub along with instructions about how to use them:

https://hub.docker.com/r/anchore/cli/

**Comment by TheCaucasianAsian** [comment]
Hi!  My installation is working flawlessly, but this instruction doesn't seem to work anymore:  `yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
`
Not sure if you advise this, but maybe just including `sudo -i` in the instructions might help mitigate the error that the OP had.  I ran into it too and had to install everything again.

**Comment by nurmi** [comment]
Thanks for the note!  I've added some text in the README to clarify that you either need to be running the package dependency installs as root or via sudo, as per your observation - thanks again!

BTW - the README is now altered to more match the installation instructions on the Anchore github wiki, which is a bit more comprehensive and worth taking a look at as well - https://github.com/anchore/anchore/wiki
