### ISSUE TITLE
Anchore List All Analyzed Containers

### ISSUE THREAD

**Issue by bryanCoteChang** [anchore/anchore#25]
I apologize in advance if this is already available, but is there a way to view everything you analyzed?  I've automated the analysis process, but just realized I couldn't find the command to view all the containers that Anchore has analyzed.

**Comment by acathrow** [comment]
You can run 
`anchore toolbox images` and you'll get a list of images that have been analyzed.

**Comment by acathrow** [comment]
You are also welcome to join our slack community at
https://anchore.com/opensource/community/#slack

**Comment by bryanCoteChang** [comment]
Awesome thank you!
