### ISSUE TITLE
Failed to analyze Docker Container with Internal Base Image

### ISSUE THREAD

**Issue by bryanCoteChang** [anchore/anchore#28]
Hi!

Any of my containers that use another one of my containers as a base image isn't being analyzed.  It also breaks `anchore query cve-scan all` query for the same reason.

As a work-around, I think I could just delete all containers where the distro is unknown, but is it possible that those containers have vulnerabilities that I might miss?

Many Thanks,
Bryan

**Comment by nurmi** [comment]
Hi Bryan!

I think it would help us if you could perhaps give us some commands/errors that you're seeing, in order for us to ensure we're attacking the same issue you're seeing.  

For example, with anchore 1.1.3, I tried the following, with imageA using 'FROM centos' and imageB using 'FROM imageA':

# anchore analyze --image imageB
# anchore query --image imageB cve-scan all

and even though imageA isn't analyzed by default in this setup, the CVE scan still was able to show results.  I also tried:

# anchore analyze --image imageA
# anchore analyze --image imageB
# anchore toolbox --image imageA delete
# anchore query --imageB cve-scan all

and this looked OK as well.  

Are you seeing an error when trying to perform a cve scan that we can take a look at? (please use --debug to get a full output to help us diagnose!)

Best
-Dan

p.s.  there is an option that you can pass to analyze called '--layerstrategy' which you can use to control the behavior of anchore when it comes to analyzing intermediate containers.  In the above example, if we were to have used 'anchore analyze --image imageB --layerstrategy All' then it would have analyzed imageA as well.  The default (without specifying a layerstrategy) is to analyze the image itself, and the base (earliest in the family tree).

**Comment by bryanCoteChang** [comment]
Hi Dan,

Woah you guys are responsive!!  Thank you for working through this with me!  Sorry for my late response!

I started to go back through and re-analyze the containers that were giving me issues yesterday and I have no explanation, but they somehow decided to get their act together.

I have a script that scans everything for me.  Should finish by tonight.  Will run a `anchore query cve-scan all` fist thing tomorrow to see if all is good.

Many Thanks,
Bryan

**Comment by bryanCoteChang** [comment]
Everything is working fine now!  Thanks again for all your help .   :)

**Comment by acathrow** [comment]
Glad to hear. We are also available on slack @
https://anchore.com/opensource/community/#slack if you need any real time
help.

**Comment by bryanCoteChang** [comment]
That's awesome!  Thanks again!  I will definitely have to reach out sometime!
