### ISSUE TITLE
Inconsistencies when downloading debian feed data

### ISSUE THREAD

**Issue by rongutierrez** [anchore/anchore#29]
It seems to be a flip of the coin for successfully downloading debian group data when running 'feeds sync' Any particular reason why? If the issue is upstream, could we maybe include a retry if a failure occurred?

Since, I'm planning to periodically build an anchore container image so that it has fresh CVE data instead of running a 'feed sync' before each scan, this could lead to an image not containing any CVE data for debian. 

Sample Output: 
[0m[91m	syncing group data: debian:unstable: ...
[0m[91m		WARN: failed to download feed/group data (vulnerabilities/debian:unstable): check --debug output and/or try again
[0m[91m	syncing group data: ubuntu:16.04: ...
[0m[91m	syncing group data: centos:6: ...
[0m[91m	syncing group data: centos:7: ...
[0m[91m	syncing group data: centos:5: ...
[0m[91m	syncing group data: ubuntu:14.10: ...
[0m[91m	syncing group data: ubuntu:15.04: ...
[0m[91m	syncing group data: debian:9: ...
[0m[91m		WARN: failed to download feed/group data (vulnerabilities/debian:9): check --debug output and/or try again
[0m[91m	syncing group data: debian:8: ...
[0m[91m		WARN: failed to download feed/group data (vulnerabilities/debian:8): check --debug output and/or try again
[0m[91m	syncing group data: ubuntu:12.04: ...
[0m[91m	syncing group data: debian:7: ...
[0m[91m		WARN: failed to download feed/group data (vulnerabilities/debian:7): check --debug output and/or try again

**Comment by nurmi** [comment]
Greetings,

We're seeing a slowdown in our back-end storage service that is causing some delays resulting in timeouts - we'll be working on a way to resolve this today and will let you know when we get it sorted!

In terms of retries - the anchore client does do retries currently (default is 3), and there is an option you can add to your anchore config.yaml to adjust the retry/timeout behavior of the clients:

feeds_conn_timeout: '10'
feeds_max_retries: '3'

We'll let you know just as soon as we make some progress on the back-end!

Best
-Dan

**Comment by nurmi** [comment]
Greetings,

We've worked to remove the timeouts we were seeing in the storage backed - please let us know if you're seeing additional feed sync/download timeouts moving forward and thank you for the catch!

Best,
-Dan

**Comment by rongutierrez** [comment]
Sweet! thanks for the quick response. I haven't run into an issue yet.
