### ISSUE TITLE
Support for private registries?

### ISSUE THREAD

**Issue by mylespollie** [anchore/anchore#31]
Will support for scanning private registries be added with the command line tools eventually?  I'd like to be able to scan my OpenShift Registry.

**Comment by acathrow** [comment]
The command line tools support scanning any docker v2 compatible registry that you have local access to. So if you install the CLI on a rhel/centos/fedora/debian/ubuntu machine/vm then you can pull the image and analyze it.
docker pull myregistry:5000/myrepo/app:latest
anchore analyze --image=myregistry:5000/myrepo/app:latest

You can also ask questions on slack here: https://anchore.com/opensource/community/#slack
