### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by lirantal** [anchore/anchore#36]
Wouldn't it make sense for a container security tool to actually have a container image that we can run the tool from instead of requiring to actually install it on a specific Linux OS?

At least from what the README shows, it's all manual installation.

**Comment by acathrow** [comment]
We do have a docker image published on DockerHub
You can find details here : https://hub.docker.com/r/anchore/cli/
We are also in the process of releasing a new version that can run as a centralized service with RESTful API. 
I'll review our Wiki and make sure we have a link to the DockerHub image. 
thanks

**Comment by lirantal** [comment]
I see you updated the README. Excellent, thank you!
