### ISSUE TITLE
How to scan Docker images through Docker REST API?

### ISSUE THREAD

**Issue by DockerAsura** [anchore/anchore#38]
How to Scan Docker images and container, using Docker reset api's using anchore?

Docker version :- 1.12.6

Thanks 
Asura

**Comment by nurmi** [comment]
Hi Asura,

Anchore currently operates against images that you have already 'pulled' to your local docker host (i.e. it does not hit a docker registry directly) - so for example a flow on a system that has docker and anchore installed would look something like:
```
# docker pull ubuntu:latest
# anchore analyze --image ubuntu:latest
# anchore query --image ubuntu:latest cve-scan all
```
Does this address your question?

Best
-Dan

**Comment by DockerAsura** [comment]
Hi Dan,
I don't want to scan my docker registry...
i want to scan images available on docker-engine only. But i want scan that through reset API method. 
Here the example :- 
When i start docker engine, usually it start's with "UNIX.sock". But docker support's api method to start Docker engine. 


thanks
Asura

**Comment by acathrow** [comment]
Asura, we're in the process of releasing a new version of the engine that's wrapped with a REST API.
If you're interested in getting early access to a version I'd love to talk - it's something I can get you started with today.
andrewc@anchore.com

**Comment by nurmi** [comment]
Asura,

I see - thank you for the clarification!  Anchore also supports configuring the docker connect string (the default is /var/run/docker.sock) by changing the following propery in ~/.anchore/conf/config.yaml (you will need to put your own value in with the right IP/port for your docker engine that is hosting the docker REST api):

```
# docker_conn: 'unix://var/run/docker.sock'
docker_conn: 'tcp://127.0.0.1:8765'
```

This will instruct the underlying dependency (python docker module) to use the given connect string instead of the default unix socket.  Note that we havn't tested the python docker module interface using tcp connect string a lot, but it does work when we have tried it!

Best
-Dan

**Comment by DockerAsura** [comment]
i given try with also..But no use,


Thanks
Asura

**Comment by acathrow** [comment]
Can you jump on slack - where we can try and help out?
https://anchore.com/opensource/community/#slack

**Comment by nurmi** [comment]
Asura,

Could you share some output showing the issue (with anchore, you can supply the --debug flag to get good debugging output)?  If you have configured docker to listen on a port and accept REST commands, then anchore (actually the docker python module) should be compatible.  

For testing, you can try the following to verify that docker is up and running, configured to accept REST api calls, in a way that should lead to anchore being able to communicate with it:

```
# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> cli = docker.Client(base_url='tcp://127.0.0.1:8765', version='auto')
>>>
```

if, for example, your system cannot communicate with your docker API endpoint, you would see an error like so:

```
# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> cli = docker.Client(base_url='tcp://127.0.0.1:8765', version='auto')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: HTTPConnectionPool(host='127.0.0.1', port=8765): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1a6f490>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by DockerAsura** [comment]
Hi,
I given try with all those steps.. But still, it throwing same error.
Error here
[root@inbpo5170 ~]# vi /usr/lib/python2.7/site-packages/anchore/cli/common.py
[root@inbpo5170 ~]# python
Python 2.7.5 (default, Aug 29 2016, 10:12:21) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> cli = docker.Client(base_url='tcp://inbpo5170.in.iisbpo.com:2375', version='auto'
... 
... 
... )
>>> cli = docker.Client(base_url='tcp://inbpo5170.in.iisbpo.com:2375', version='auto')
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> 
[root@inbpo5170 ~]# anchore --debug analyze
2017-08-07 20:20:18,916 DEBUG anchore_image_db_fs.py __init__ using directory for anchore image data: /root/.anchore/data
2017-08-07 20:20:18,916 DEBUG anchore_image_db_fs.py __init__ using directory for anchore feed data: /root/.anchore/feeds
2017-08-07 20:20:18,918 DEBUG auth.py find_config_file Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2017-08-07 20:20:18,918 DEBUG auth.py find_config_file Found file at path: /root/.docker/config.json
2017-08-07 20:20:18,918 DEBUG auth.py load_config Found 'auths' section
2017-08-07 20:20:18,918 DEBUG auth.py parse_auth Found entry (registry=u'inbpo5170.in.iisbpo.com:5002', username=u'admin')
2017-08-07 20:20:18,918 DEBUG auth.py parse_auth Found entry (registry=u'inbpo5170.in.iisbpo.com:5000', username=u'admin')
2017-08-07 20:20:18,918 DEBUG auth.py parse_auth Found entry (registry=u'inbpo5170.in.iisbpo.com:5002', username=u'admin')
2017-08-07 20:20:18,925 DEBUG anchore_image_db_fs.py __init__ using directory for anchore image data: /root/.anchore/data
2017-08-07 20:20:18,925 DEBUG anchore_image_db_fs.py __init__ using directory for anchore feed data: /root/.anchore/feeds
2017-08-07 20:20:18,927 ERROR common.py anchore_print_err could not load any images
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore/cli/analyzer.py", line 301, in analyze
    imagedict = build_image_list(anchore_config, image, imagefile, not (image or imagefile), include_allanchore, exclude_file=excludefile, dockerfile=dockerfile)
  File "/usr/lib/python2.7/site-packages/anchore/cli/common.py", line 156, in build_image_list
    raise Exception("Could not load any images from local docker host - is docker running?")
Exception: Could not load any images from local docker host - is docker running?

**Comment by DockerAsura** [comment]
Steps here to resolve 

1.) python 
####Excute python command on your termenial, it will open python console.. then excute command's#######
# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
######inside python console commands######
>>> import docker
>>> cli = docker.Client(base_url='tcp://127.0.0.1:8765', version='auto')
####Press "crtl+d" to come out of python console#######

2.) edit default config file of anchore ~/.anchore/conf/config.yaml
uncommonet in 'docker_conn' line. And add you docker engine API 
ex:- docker_conn: 'tcp://127.0.0.1:8765'
Save file 
Now excute anchore analyze or 'anchore' commands

OR

2.) you can also excute command to overwite your default configurtion 
ex:- anchore --config-override docker_conn='tcp://127.0.0.1:8765' --debug analyze


Thanks a lot @nurmi 


Thanks
Asura
