### ISSUE TITLE
alpine:3.7 not supported

### ISSUE THREAD

**Issue by gruebel** [anchore/anchore#49]
Hi,

do you have any plans to add the new version of alpine to your supported distro list?

Would be great :)

**Comment by nurmi** [comment]
Hi @gruebel 

One of the main sources that anchore triggers off of to be able to add security feeds for new alpine versions is the secdb records from alpine (https://git.alpinelinux.org/cgit/alpine-secdb/).  As soon as the new version of alpine shows up there, then we'll add support in anchore as well shortly thereafter.

One thing to not is that, as soon as alpine adds 3.7 to their sec db, and anchore starts consuming that feed, you will not need to update any anchore software bits as the new feed/mapping will start happening automatically (after the next anchore feed sync that pulls in 3.7).

Thanks for making a note here, I think we should keep this ticket open until upstream (alpine) starts publishing data for 3.7 and anchore brings it in.

Best,
Dan

**Comment by gruebel** [comment]
Hi Dan,

thanks for the quick reply!

**Comment by gruebel** [comment]
Hi Dan,

they finally added the data for 3.7.
