### ISSUE TITLE
sample jenkins integration

### ISSUE THREAD

**Issue by SyCode7** [anchore/anchore#52]
The documentation says there is support for jenkins integration, is there some example how this works or a blog post ?

**Comment by zhill** [comment]
Hi @SyCode7 , the docs for the Anchore Jenkins plugin are at the [jenkins wiki](https://wiki.jenkins.io/display/JENKINS/Anchore+Container+Image+Scanner+Plugin) and an overview on this wiki [here](https://github.com/anchore/anchore/wiki/Anchore-and-Jenkins-Integration). There are two modes of operation: anchore local (runs anchore in a container in jenkins worker) or engine-mode which uses the [anchore-engine](https://github.com/anchore/anchore-engine) service running outside the jenkins worker to do the analysis and report results.

**Comment by SyCode7** [comment]
@zhill many thanks for your response and also for this excellent tool . I am a bit new to Jenkins so I was hoping to find a  "work through"  example that integrates anchore into Jenkins security tests for example in  a continuous integration pipeline (using a Jenkinsfile).

**Comment by nurmi** [comment]
Hi @SyCode7 

We don't have a full walkthrough document using the pipeline method for anchore, however we do indeed support using the anchore jenkins plugin withing  a pipeline script!  The link @zhill  provided is a good place to start to understand the way that the anchore plugin fits into your CI/CD flow, and then you can script this flow using Jenkinsfile/pipeline with the anchore scan step placed appropriately after your regular container build/push at any point.  There is a quick example pipeline format for the anchore plugin here:  https://github.com/jenkinsci/anchore-container-scanner-plugin

Let us know if you encounter any blockers when adding anchore to your pipeline, we're happy to discuss - and perhaps our discussion could even turn into a guide for others!

**Comment by SyCode7** [comment]
@nurmi https://github.com/jenkinsci/anchore-container-scanner-plugin helps a lot. I will surely get back if i face challenges. Thanks 👍
