### ISSUE TITLE
Docker image not getting anlyzed with anchore-engine

### ISSUE THREAD

**Issue by vedaprasad** [anchore/anchore#60]
Hi , 

I have setup anchore-engine using docker-compose but i am not able to analyze any image.

Docker-compose ps

         Name                   Command                   State                    Ports
-------------------------------------------------------------------------------------------------
aevolume_anchore-db_1    docker-entrypoint.sh     Up                       5432/tcp
                         postgres
aevolume_anchore-        /bin/sh -c               Up                       0.0.0.0:8083->8083/tcp
engine_1                 /usr/bin/anchor ...                               , 0.0.0.0:8084->8084/t
                                                                           cp, 0.0.0.0:8087->8087
                                                                           /tcp, 0.0.0.0:8228->82
                                                                           28/tcp,
                                                                           0.0.0.0:8338->8338/tcp

when i add the image it always returns status as not_analyzed.
anchore-cli image add registry.gitlab.com/its_vedu/nginx-docker:latest
Image Digest: sha256:21a54b24b692dd1b7e7acc623ade182b649a12cbc63eb090abc801d5556c58d4
Analysis Status: not_analyzed
Image Type: docker
Image ID: de278a11a415411431f9ca81a14ca2a6250a7cf03576c09236b0d6d37a8c587f
Dockerfile Mode: None
Distro: None
Distro Version: None
Size: None
Architecture: None
Layer Count: None

Full Tag: registry.gitlab.com/its_vedu/nginx-docker:latest
 i came to know if the imaged in queued it goes to not_analyzed state and hence managed to get some logs .

anchore-engine_1  | [service:simplequeue] 2018-07-25 23:09:00+0000 [-] "172.18.0.3" - - [25/Jul/2018:23:09:00 +0000] "POST /v1/queues/watcher_tasks/is_inqueue HTTP/1.1" 200 3 "-" "python-requests/2.17.3"
anchore-engine_1  | [service:simplequeue] 2018-07-25 23:09:00+0000 [-] "172.18.0.3" - - [25/Jul/2018:23:09:00 +0000] "POST /v1/queues/watcher_tasks/?qcount=0&forcefirst=False HTTP/1.1" 200 5 "-" "python-requests/2.17.3"

anchore-engine_1  | [service:simplequeue] 2018-07-25 23:09:28+0000 [-] "172.18.0.3" - - [25/Jul/2018:23:09:28 +0000] "GET /v1/leases/analyzer_queue/release/?client_id=d1ea844bb62d:17:140187329885952:&epoch=2302[service:policy_engine] 2018-07-25 23:09:29+0000 [-] [bootstrap] [INFO] Registration complete.
anchore-engine_1  | [service:policy_engine] 2018-07-25 23:09:29+0000 [-] [bootstrap] [INFO] Checking feeds client credentials

anchore-engine_1  | Traceback (most recent call last):
anchore-engine_1  |   File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
anchore-engine_1  |     raise Exception("process exited: " + str(rc))
anchore-engine_1  | Exception: process exited: 1
anchore-engine_1  | [anchore-policy-engine] [anchore_manager.cli.service/startup_service()] [INFO] service process exited at (Wed Jul 25 23:09:30 2018): process exited: 1
anchore-engine_1  | [anchore-policy-engine] [anchore_manager.cli.service/startup_service()] [INFO] exiting service thread

Any help is greatly appreciated.

Thanks,
VedaPrasad

**Comment by nurmi** [comment]
hi @vedaprasad!

This project is for the older 'anchore' toolkit/scanning, while the current anchore software is over at https://github.com/anchore/anchore-engine

Would you mind moving this request over to that project?  I suspect that the issue is that the policy engine service isn't coming up (you can review by running ```anchore-cli system status```) because it requires network access to https://ancho.re on startup by default.  There are a few tickets/discussions on this condition and workarounds over in the anchore-engine project!

**Comment by vedaprasad** [comment]
@nurmi : Sure will do that , also looks like an issue as you pointed out 

root@ubuntu-xenial:~/aevolume# anchore-cli system status
Service simplequeue (dockerhostid-anchore-engine, http://anchore-engine:8083): up
Service apiext (dockerhostid-anchore-engine, http://anchore-engine:8228): up
Service kubernetes_webhook (dockerhostid-anchore-engine, http://anchore-engine:8338): up
Service analyzer (dockerhostid-anchore-engine, http://anchore-engine:8084): up
Service catalog (dockerhostid-anchore-engine, http://anchore-engine:8082): up
Service policy_engine (dockerhostid-anchore-engine, http://anchore-engine:8087): down (unavailable)
