### ISSUE TITLE
Issue Adding Images

### ISSUE THREAD

**Issue by leetsg0** [anchore/anchore#62]
Hello,

I've been having an issue with the anchore engine scanning a local image in my local registry.  I'm getting the following error.

Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {u'raw_exception_message': u'could not get manifest/digest for image (localhost:5000/textron:latest) from registry (https://localhost:5000) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://localhost:5000/textron:latest, rc=1, stdout=None, stderr=b\'time="2019-03-28T16:28:14Z" level=fatal msg="pinging docker registry returned: Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused" \\n\''}

The image is not one that I created but one that has been provided to me.

Leets

**Comment by zhill** [comment]
@leetsg0 that looks like the anchore container cannot reach the registry. I'm assuming you're running the registry as a container as well, so you'll need to make sure that the registry container is on the same docker network as the anchore container, and then you'll want to use the container name as the dns name you give anchore to analyze the image (e.g. myregistrycontainer:5000/textron:latest) rather than localhost since docker uses the container names for dns in inter-container connectivity and localhost is not shared between containers in a regular docker deployment.

To test you can exec into the anchore container and try running `skopeo inspect <reg/repo:tag>` to see if it is reachable from that name until you get it, then just use that in the anchore-cli commands and it should work.

**Comment by nurmi** [comment]
hi @leetsg0 - that error is telling us that the input image registry portion is 'localhost:5000', which is likely not what is intended as 'localhost' will resolve to the anchore-engine container internal address itself looking for a registry there.   You'll likely need to add the image with a registry hostname/ip/port that is the endpoint accessible to the engine (what you would use for a regular 'docker pull' for example).  If the registry requires credenditals, there is also an additional step to configure anchore-engine with the credential so that it can access the referenced registry: https://anchore.freshdesk.com/support/solutions/articles/36000003888-configuring-access-to-registries

**Comment by leetsg0** [comment]
@zhill, you're correct I'm running the registry as a container.  So here's what I've done so far:

1) Made sure that the registry container is connected in the same docker container as the anchore container by running: $ docker network connect registry
and verified by running: $ docker network connect inspect aevolume_default

2) The container name has been changed to (i used your example) myregistrycontainer:5000/textron

3) I tried running the skopeo command and got the following error:
ime="2019-03-28T19:27:35Z" level=fatal msg="Invalid image name "myregistrycontainer:5000/textron", unknown transport "myregistrycontainer""

4) I tried re-running the cli image add and got the following error:
Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {u'raw_exception_message': u'could not get manifest/digest for image (myregistrycontainer:5000/textron:latest) from registry (https://myregistrycontainer:5000) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://myregistrycontainer:5000/textron:latest, rc=1, stdout=None, stderr=b\'time="2019-03-28T19:33:44Z" level=fatal msg="pinging docker registry returned: Get http://myregistrycontainer:5000/v2/: dial tcp: lookup myregistrycontainer on 127.0.0.11:53: no such host" \\n\''}

Any thoughts on what I did wrong.

Thanks,
Leets

**Comment by zhill** [comment]
@leetsg0 looks like two things:
1. My bad, incorrect skopeo example, should use `skopeo inspect docker://myregistrycontainer:5000/textron:latest` and that should work. The error is is a mal-formed input string, skopeo specifically requires the 'docker://' prefix.
2. It looks like there is a dns lookup failing (see the port 53), which means the host name you're using may not be correct. You can try simple `curl http://myregistrycontainer:5000/v2/_catalog` to verify that it can reach it. That should return the listing of your repositories on the registry. My guess is that the connect command didn't do what you wanted. Maybe `docker network connect aevolume_default myregistrycontainer`?

Here are my steps on my dev system (engine-dev is the network name my running container uses):
On my host:
```
zhill@overthinkpad]$ docker pull registry
Using default tag: latest
latest: Pulling from library/registry
c87736221ed0: Pull complete 
1cc8e0bb44df: Pull complete 
54d33bcb37f5: Pull complete 
e8afc091c171: Pull complete 
b4541f6d3db6: Pull complete 
Digest: sha256:3b00e5438ebd8835bcfa7bf5246445a6b57b9a50473e89c02ecc8e575be3ebb5
Status: Downloaded newer image for registry:latest

[zhill@overthinkpad]$ docker run -d -p 5000:5000 --name myregistrycontainer registry
14f0d7482f477d74e800a6f85c4e1e5152770a9f68bd8f22cfc027be1bc6a219

[zhill@overthinkpad ]$ docker network connect engine-dev myregistrycontainer

[zhill@overthinkpad ]$ docker tag registry localhost:5000/registry:latest

[zhill@overthinkpad ]$ docker push localhost:5000/registry:latest
The push refers to repository [localhost:5000/registry]
73d61bf022fd: Pushed 
5bbc5831d696: Pushed 
d5974ddb5a45: Pushed 
f641ef7a37ad: Pushed 
d9ff549177a9: Pushed 
latest: digest: sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774 size: 1363

```

In my container running anchore:
```
root@179b970c1e9c:~# skopeo inspect docker://myregistrycontainer:5000/registry:latest
FATA[0000] pinging docker registry returned: Get https://myregistrycontainer:5000/v2/: http: server gave HTTP response to HTTPS client
 
root@179b970c1e9c:~# root@179b970c1e9c:~#: anchore-cli image add myregistrycontainer:5000/registry:latest:
Image Digest: sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774
Parent Digest: sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774
Analysis Status: not_analyzed
Image Type: docker
Image ID: f32a97de94e13d29835a19851acd6cbc7979d1d50f703725541e44bb89a1ce91
Dockerfile Mode: None
Distro: None
Distro Version: None
Size: None
Architecture: None
Layer Count: None

Full Tag: myregistrycontainer:5000/registry:latest


root@179b970c1e9c:~# anchore-cli image list
Full Tag                                        Image Digest                                                                   Analysis Status        
docker.io/alpine:latest                         sha256:d05ecd4520cab5d9e5d877595fb0532aadcd6c90f4bbc837bc11679f704c4c82        analyzed               
myregistrycontainer:5000/registry:latest        sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774        analyzing              
root@179b970c1e9c:~# 

```

You're close, and note that the skopeo call still returns an error, but the HTTP on HTTPS resopnse is ok, anchore will handle that properly internally, but at least skopeo got a response.

**Comment by leetsg0** [comment]
@zhill and @nurmi thanks for the help guys.  I went ahead and put the container on an external (endpoint) registry, did waht @nurmi suggested and add the image that way.  It worked.  I may try your solution, @zhill but for now I'm good.  Thanks again.

**Comment by zhill** [comment]
@leetsg0 also note (i just realized this), these issues should be in the https://github.com/anchore/anchore-engine repo, this is the old CLI tool that is deprecated. I'll move this issue over for clarity.
