### ISSUE TITLE
Incorrect packages list on Debian & false positive

### ISSUE THREAD

**Issue by guedou** [anchore/anchore#63]
anchore does not take packages status into account while listing packages (see https://github.com/anchore/anchore/blob/8a4d5b9708e27856312d303aae3f04f3c72039d6/anchore/anchore-modules/analyzers/11_package_detail_list.py#L36). This leads to false positive when a package is marked as rc (i.e. removed).

I wll suggest that you also retrieve ${Status} variables and filter out packages marked as "deinstall".

**Comment by zhill** [comment]
Thanks! I think this should probably go in the [anchore-engine](https://github.com/anchore/anchore-engine) repo. Are you using the restful service or this code (`anchore ...` instead of `anchore-cli`)

**Comment by guedou** [comment]
Thanks. I open an issue on anchore/anchore-engine
