### ISSUE TITLE
Error while scanning docker image locally

### ISSUE THREAD

**Issue by ethicalmohit** [anchore/anchore#64]
I am trying to scan the docker image. But I am getting below error while trying to scan a project. However, the file exists on that particular location.

``` 
aevolume mohit$ docker-compose exec engine-api anchore-cli image add image:latest --dockerfile=/Users/mohit/project/Dockerfile.base
Usage: anchore-cli image add [OPTIONS] INPUT_IMAGE
Try "anchore-cli image add --help" for help.

Error: Invalid value for "--dockerfile": Path "/Users/mohit/project/Dockerfile.base" does not exist.
```

**Comment by nurmi** [comment]
hi @ethicalmohit - we've connected on other channels, so I'll close this ticket out ( the project has moved to https://github.com/anchore/anchore-engine ).
